from __future__ import annotations

import logging
import re
from collections import Counter

from .header_footer import HeaderFooterResult
from .models import Block, DocumentMetadata, Page

logger = logging.getLogger(__name__)

# A Vietnamese enterprise's legal name almost always contains one of these
# entity-type tokens ("Joint Stock Company", "Limited Liability Company",
# "Corporation", "Group", ...). Used to pick the company name out of the
# repeating header lines rather than guessing at position/casing alone.
_COMPANY_MARKER_RE = re.compile(
    r"\b(CÔNG TY|CTY|TẬP ĐOÀN|TỔNG CÔNG TY)\b", re.IGNORECASE
)

# Plausible fiscal years for a report generated by this pipeline today.
_YEAR_RE = re.compile(r"\b(19[9]\d|20[0-4]\d)\b")

# Phrases that typically precede/anchor the reporting year in a Vietnamese
# audited financial statement's title or opening paragraph.
_YEAR_CONTEXT_RE = re.compile(
    r"(năm tài chính|năm\s+kết thúc|cho năm|niên độ|báo cáo\s+năm)",
    re.IGNORECASE,
)


class MetadataExtractor:
    """Extracts document-level and block-level metadata deterministically."""

    def __init__(self, cover_page_scan_limit: int = 3) -> None:
        """``cover_page_scan_limit``: how many leading pages count as the
        "cover" for company-name/year extraction (title pages in these
        reports are almost always within the first few pages).
        """
        self.cover_page_scan_limit = cover_page_scan_limit

    def extract_document_metadata(
        self,
        pages: list[Page],
        header_footer_result: HeaderFooterResult,
        source_file: str | None = None,
    ) -> DocumentMetadata:
        """Build document-level :class:`DocumentMetadata`."""
        company_name = self._extract_company_name(pages, header_footer_result)
        report_year = self._extract_report_year(pages)

        metadata = DocumentMetadata(
            company_name=company_name,
            report_year=report_year,
            source_file=source_file,
            page_count=len(pages),
            detected_headers=tuple(
                header_footer_result.examples[k]
                for k in sorted(header_footer_result.header_keys)
                if k in header_footer_result.examples
            ),
            detected_footers=tuple(
                header_footer_result.examples[k]
                for k in sorted(header_footer_result.footer_keys)
                if k in header_footer_result.examples
            ),
        )
        logger.info(
            "Extracted document metadata: company_name=%r, report_year=%r, "
            "pages=%d.",
            metadata.company_name,
            metadata.report_year,
            metadata.page_count,
        )
        return metadata

    def _extract_company_name(
        self, pages: list[Page], header_footer_result: HeaderFooterResult
    ) -> str | None:
        # Preference 1: a detected repeating header/footer line containing
        # a company-entity marker — this is the letterhead, which is the
        # most reliable signal since it recurs on nearly every page.
        # Sort keys before resolving to text: iterating a `set` directly has
        # an order that depends on Python's per-process string hash seed,
        # which would make the "pick the longest candidate" choice below
        # non-deterministic across runs whenever two candidates tie in
        # length. Sorting first removes that dependency entirely.
        all_keys = sorted(
            header_footer_result.header_keys | header_footer_result.footer_keys
        )
        candidates = [
            header_footer_result.examples[k]
            for k in all_keys
            if k in header_footer_result.examples
        ]
        marked = [c for c in candidates if _COMPANY_MARKER_RE.search(c)]
        if marked:
            # Prefer the longest match — Vietnamese legal names are often
            # split across a short and a fuller header line; the fuller one
            # is more likely to be the complete legal name. Ties broken
            # alphabetically for full determinism.
            return sorted(marked, key=lambda c: (-len(c), c))[0].strip()

        # Preference 2: scan cover pages directly for a line carrying the
        # company marker (covers documents too short for frequency-based
        # header/footer detection to have kicked in at all).
        for page in pages[: self.cover_page_scan_limit]:
            for line in page.text.split("\n"):
                if _COMPANY_MARKER_RE.search(line):
                    return line.strip()

        return None

    def _extract_report_year(self, pages: list[Page]) -> int | None:
        year_counts: Counter[int] = Counter()
        for page in pages[: self.cover_page_scan_limit]:
            for line in page.text.split("\n"):
                if not _YEAR_CONTEXT_RE.search(line):
                    continue
                for match in _YEAR_RE.finditer(line):
                    year_counts[int(match.group(1))] += 1

        if not year_counts:
            # Fall back to the most frequent plausible year anywhere on the
            # cover pages, context phrase or not.
            for page in pages[: self.cover_page_scan_limit]:
                for match in _YEAR_RE.finditer(page.text):
                    year_counts[int(match.group(1))] += 1

        if not year_counts:
            return None
        return year_counts.most_common(1)[0][0]
    
    @staticmethod
    def assign_block_sections(blocks: list[Block]) -> None:
        """Gắn section/subsection từ heading_path; forward-fill nếu path trống."""
        last_path: tuple[str, ...] = ()
        for block in blocks:
            path = block.heading_path
            if path:
                last_path = path
            elif last_path:
                block.heading_path = last_path
                path = last_path
            block.section = path[0] if len(path) >= 1 else None
            block.subsection = path[1] if len(path) >= 2 else None