from dotenv import load_dotenv
import os

load_dotenv()

# Mongo
#MONGO_URI_LOCAL = os.getenv("MONGO_URI_LOCAL", "mongodb://localhost:27017")
MONGO_URI_CLOUD = os.getenv("MONGO_URI_CLOUD")
MONGO_DB_DOCUMENTS = os.getenv("MONGO_DB_DOCUMENTS", "financial_rag")
MONGO_DB_CHUNKS = os.getenv("MONGO_DB_CHUNKS", "financial_rag_corrected")
DOCUMENTS_COLLECTION = os.getenv("DOCUMENTS_COLLECTION", "documents_2025")
MONGO_URI_HISTORY: str = os.getenv("MONGO_URI_HISTORY")
MONGO_DB_HISTORY: str = os.getenv("MONGO_DB_HISTORY", "fin_rag_history")
# Qdrant
QDRANT_URL = os.getenv("QDRANT_URL")
QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")
QDRANT_COLLECTION = os.getenv("QDRANT_COLLECTION", "financial_chunks")
VECTOR_SIZE = 1024

# Embedding
EMBEDDING_MODEL_ID = os.getenv("EMBEDDING_MODEL_ID", "BAAI/bge-m3")
EMBEDDING_BATCH_SIZE = int(os.getenv("EMBEDDING_BATCH_SIZE", "12"))
EMBEDDING_MAX_LENGTH = int(os.getenv("EMBEDDING_MAX_LENGTH", "8192"))
EMBEDDING_USE_FP16 = os.getenv("EMBEDDING_USE_FP16", "auto")

# LLM / Rerank (bổ sung)
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
RERANKER_MODEL_NAME = os.getenv("RERANKER_MODEL_NAME", "BAAI/bge-reranker-v2-m3")

# Alias dùng chung (mongo_client / hybrid có thể đọc MONGO_URI)
#MONGO_URI = os.getenv("MONGO_URI") or MONGO_URI_LOCAL
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

class Settings:
    # Mongo
    #MONGO_URI_LOCAL = MONGO_URI_LOCAL
    MONGO_URI_CLOUD = MONGO_URI_CLOUD
    #MONGO_URI = MONGO_URI
    MONGO_DB_DOCUMENTS = MONGO_DB_DOCUMENTS
    MONGO_DB_CHUNKS = MONGO_DB_CHUNKS
    DOCUMENTS_COLLECTION = DOCUMENTS_COLLECTION
    MONGO_URI_HISTORY = MONGO_URI_HISTORY
    MONGO_DB_HISTORY = MONGO_DB_HISTORY

    # Qdrant
    QDRANT_URL = QDRANT_URL
    QDRANT_API_KEY = QDRANT_API_KEY
    QDRANT_COLLECTION = QDRANT_COLLECTION
    VECTOR_SIZE = VECTOR_SIZE

    # Embedding
    EMBEDDING_MODEL_ID = EMBEDDING_MODEL_ID
    EMBEDDING_BATCH_SIZE = EMBEDDING_BATCH_SIZE
    EMBEDDING_MAX_LENGTH = EMBEDDING_MAX_LENGTH
    EMBEDDING_USE_FP16 = EMBEDDING_USE_FP16

    # LLM / Rerank
    GROQ_API_KEY = GROQ_API_KEY
    RERANKER_MODEL_NAME = RERANKER_MODEL_NAME
    OPENAI_API_KEY: str = OPENAI_API_KEY


settings = Settings()